server:
  port: 8080
  servlet:
    # Quy định cho mỗi microservice
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_URL:jdbc:mysql://localhost:3306/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    # Cấu hình jpa tự gen table
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 # (s) Thgian hợp lệ của một token
  refreshable-duration: 36000 # Trong khoảng thgian này mình có thể refresh một token (thường là day)